using BuildingManagement.Domain;
using Microsoft.EntityFrameworkCore;

namespace BuildingManagement.Application;

public sealed class FinancialAccountService(IApplicationDbContext db, TimeProvider clock) : FinancialServiceBase(db, clock)
{
    public async Task<FinancialAccountResponse> Create(FinancialAccountRequest request, CancellationToken ct) { if (request is null) throw Validation("request", "Required."); var count = (string.IsNullOrWhiteSpace(request.UnitCode) ? 0 : 1) + (string.IsNullOrWhiteSpace(request.BuildingCode) ? 0 : 1) + (string.IsNullOrWhiteSpace(request.ComplexCode) ? 0 : 1); if (count != 1) throw Validation("owner", "Exactly one owner code is required."); long? unit = null, building = null, complex = null; string owner; if (request.UnitCode is not null) { owner = Code(request.UnitCode); unit = await Db.Units.Where(x => x.Code == owner).Select(x => (long?)x.Id).SingleOrDefaultAsync(ct) ?? throw AppException.NotFound("unit"); } else if (request.BuildingCode is not null) { owner = Code(request.BuildingCode); building = await Db.Buildings.Where(x => x.Code == owner).Select(x => (long?)x.Id).SingleOrDefaultAsync(ct) ?? throw AppException.NotFound("building"); } else { owner = Code(request.ComplexCode!); complex = await Db.Complexes.Where(x => x.Code == owner).Select(x => (long?)x.Id).SingleOrDefaultAsync(ct) ?? throw AppException.NotFound("complex"); } var entity = new FinancialAccount(unit, building, complex, request.AccountKindKey, Now); Db.FinancialAccounts.Add(entity); await Save(ct); return new(owner, entity.AccountKindKey, entity.CurrentBalance, entity.IsActive); }
    public async Task<FinancialAccountResponse> Get(string ownerCode, string kind, CancellationToken ct) { var account = await AccountByOwner(ownerCode, kind, ct); return new(Code(ownerCode), kind, account.CurrentBalance, account.IsActive); }
    public async Task<IReadOnlyList<FinancialEntryResponse>> Statement(string ownerCode, string kind, CancellationToken ct) { var account = await AccountByOwner(ownerCode, kind, ct); return await Db.FinancialTransactionEntries.AsNoTracking().Where(x => x.FinancialAccountId == account.Id).OrderByDescending(x => x.CreatedAtUtc).Select(x => new FinancialEntryResponse(Db.FinancialTransactions.Where(t => t.Id == x.FinancialTransactionId).Select(t => t.TransactionTypeKey).Single(), x.EffectKey, x.Amount, x.BalanceAfter, Db.FinancialTransactions.Where(t => t.Id == x.FinancialTransactionId).Select(t => t.OccurredAtUtc).Single(), Db.FinancialTransactions.Where(t => t.Id == x.FinancialTransactionId).Select(t => t.Description).Single())).ToListAsync(ct); }
    public async Task<AccountAdjustmentResponse> CreateAdjustment(AccountAdjustmentRequest request, CancellationToken ct) { if (request.AdjustmentTypeKey is not (FinancialKeys.Adjustments.OpeningDebt or FinancialKeys.Adjustments.OpeningCredit)) throw Validation("adjustmentTypeKey", "Only opening debt and opening credit are supported in this release."); var account = await AccountByOwner(request.FinancialAccountOwnerCode, request.AccountKindKey, ct); var adjustment = new AccountAdjustment(await Unique(Db.AccountAdjustments, ct), account.Id, request.AdjustmentTypeKey, request.Amount, request.EffectiveDate, request.Reason, Now); Db.AccountAdjustments.Add(adjustment); await Save(ct); return new(adjustment.Code, adjustment.Status, adjustment.Amount, adjustment.AdjustmentTypeKey); }
    public async Task<AccountAdjustmentResponse> FinalizeAdjustment(string code, CancellationToken ct) => await Db.ExecuteInTransaction<AccountAdjustmentResponse>(async token => { var adjustment = await Db.AccountAdjustments.SingleOrDefaultAsync(x => x.Code == Code(code), token) ?? throw AppException.NotFound("account_adjustment"); if (await Db.FinancialTransactions.AnyAsync(x => x.AccountAdjustmentId == adjustment.Id, token)) return new(adjustment.Code, adjustment.Status, adjustment.Amount, adjustment.AdjustmentTypeKey); var account = await Db.FinancialAccounts.SingleAsync(x => x.Id == adjustment.FinancialAccountId, token); var effect = adjustment.AdjustmentTypeKey == FinancialKeys.Adjustments.OpeningDebt ? FinancialKeys.Effects.Decrease : FinancialKeys.Effects.Increase; adjustment.Finalize(Now); var tx = new FinancialTransaction(FinancialKeys.TransactionTypes.AccountAdjustment, null, null, null, adjustment.Id, adjustment.EffectiveDate, adjustment.Reason, Now); Db.FinancialTransactions.Add(tx); await Apply(account, effect, adjustment.Amount, tx, token); await Save(token); return new(adjustment.Code, adjustment.Status, adjustment.Amount, adjustment.AdjustmentTypeKey); }, ct);
}
