using BuildingManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#pragma warning disable CA1725 // Compact mappings use a conventional short builder name.

namespace BuildingManagement.Infrastructure;

public sealed class ExpenseDocumentConfiguration : IEntityTypeConfiguration<ExpenseDocument> { public void Configure(EntityTypeBuilder<ExpenseDocument> b) { FinancialConfiguration.Record(b, "ExpenseDocuments"); b.Property(x => x.Title).HasMaxLength(200); b.Property(x => x.Description).HasMaxLength(500); b.HasIndex(x => new { x.ExpenseId, x.StoredFileId }).IsUnique(); b.HasOne<Expense>().WithMany().HasForeignKey(x => x.ExpenseId).OnDelete(DeleteBehavior.Restrict); b.HasOne<StoredFile>().WithMany().HasForeignKey(x => x.StoredFileId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ExpenseDisbursementFileConfiguration : IEntityTypeConfiguration<ExpenseDisbursementFile> { public void Configure(EntityTypeBuilder<ExpenseDisbursementFile> b) { FinancialConfiguration.Record(b, "ExpenseDisbursementFiles"); b.Property(x => x.Title).HasMaxLength(200); b.HasIndex(x => new { x.ExpenseDisbursementId, x.StoredFileId }).IsUnique(); b.HasOne<ExpenseDisbursement>().WithMany().HasForeignKey(x => x.ExpenseDisbursementId).OnDelete(DeleteBehavior.Restrict); b.HasOne<StoredFile>().WithMany().HasForeignKey(x => x.StoredFileId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class PaymentEvidenceFileConfiguration : IEntityTypeConfiguration<PaymentEvidenceFile> { public void Configure(EntityTypeBuilder<PaymentEvidenceFile> b) { FinancialConfiguration.Record(b, "PaymentEvidenceFiles"); b.Property(x => x.Title).HasMaxLength(200); b.Property(x => x.Description).HasMaxLength(500); b.HasIndex(x => new { x.PaymentId, x.StoredFileId }).IsUnique(); b.HasOne<Payment>().WithMany().HasForeignKey(x => x.PaymentId).OnDelete(DeleteBehavior.Restrict); b.HasOne<StoredFile>().WithMany().HasForeignKey(x => x.StoredFileId).OnDelete(DeleteBehavior.Restrict); } }

public sealed class ExpenseAssetConfiguration : IEntityTypeConfiguration<ExpenseAsset> { public void Configure(EntityTypeBuilder<ExpenseAsset> b) { b.ToTable("ExpenseAssets", "bms"); b.HasKey(x => new { x.ExpenseId, x.AssetId }); b.HasOne<Expense>().WithMany().HasForeignKey(x => x.ExpenseId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Asset>().WithMany().HasForeignKey(x => x.AssetId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ExpenseAssetEventConfiguration : IEntityTypeConfiguration<ExpenseAssetEvent> { public void Configure(EntityTypeBuilder<ExpenseAssetEvent> b) { b.ToTable("ExpenseAssetEvents", "bms"); b.HasKey(x => new { x.ExpenseId, x.AssetEventId }); b.HasOne<Expense>().WithMany().HasForeignKey(x => x.ExpenseId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AssetEvent>().WithMany().HasForeignKey(x => x.AssetEventId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ExpenseBuildingConfiguration : IEntityTypeConfiguration<ExpenseBuilding> { public void Configure(EntityTypeBuilder<ExpenseBuilding> b) { b.ToTable("ExpenseBuildings", "bms"); b.HasKey(x => new { x.ExpenseId, x.BuildingId }); b.HasOne<Expense>().WithMany().HasForeignKey(x => x.ExpenseId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Building>().WithMany().HasForeignKey(x => x.BuildingId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ExpenseComplexConfiguration : IEntityTypeConfiguration<ExpenseComplex> { public void Configure(EntityTypeBuilder<ExpenseComplex> b) { b.ToTable("ExpenseComplexes", "bms"); b.HasKey(x => new { x.ExpenseId, x.ComplexId }); b.HasOne<Expense>().WithMany().HasForeignKey(x => x.ExpenseId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Complex>().WithMany().HasForeignKey(x => x.ComplexId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class DemandExpenseConfiguration : IEntityTypeConfiguration<DemandExpense> { public void Configure(EntityTypeBuilder<DemandExpense> b) { b.ToTable("DemandExpenses", "bms"); b.HasKey(x => new { x.DemandId, x.ExpenseId }); b.Property(x => x.RelatedAmount).HasPrecision(18, 2); b.HasOne<Demand>().WithMany().HasForeignKey(x => x.DemandId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Expense>().WithMany().HasForeignKey(x => x.ExpenseId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class DemandAssetConfiguration : IEntityTypeConfiguration<DemandAsset> { public void Configure(EntityTypeBuilder<DemandAsset> b) { b.ToTable("DemandAssets", "bms"); b.HasKey(x => new { x.DemandId, x.AssetId }); b.HasOne<Demand>().WithMany().HasForeignKey(x => x.DemandId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Asset>().WithMany().HasForeignKey(x => x.AssetId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class DemandAssetEventConfiguration : IEntityTypeConfiguration<DemandAssetEvent> { public void Configure(EntityTypeBuilder<DemandAssetEvent> b) { b.ToTable("DemandAssetEvents", "bms"); b.HasKey(x => new { x.DemandId, x.AssetEventId }); b.HasOne<Demand>().WithMany().HasForeignKey(x => x.DemandId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AssetEvent>().WithMany().HasForeignKey(x => x.AssetEventId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class DemandBuildingConfiguration : IEntityTypeConfiguration<DemandBuilding> { public void Configure(EntityTypeBuilder<DemandBuilding> b) { b.ToTable("DemandBuildings", "bms"); b.HasKey(x => new { x.DemandId, x.BuildingId }); b.HasOne<Demand>().WithMany().HasForeignKey(x => x.DemandId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Building>().WithMany().HasForeignKey(x => x.BuildingId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class DemandComplexConfiguration : IEntityTypeConfiguration<DemandComplex> { public void Configure(EntityTypeBuilder<DemandComplex> b) { b.ToTable("DemandComplexes", "bms"); b.HasKey(x => new { x.DemandId, x.ComplexId }); b.HasOne<Demand>().WithMany().HasForeignKey(x => x.DemandId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Complex>().WithMany().HasForeignKey(x => x.ComplexId).OnDelete(DeleteBehavior.Restrict); } }

public sealed class FinancialTransactionSourceConfiguration : IEntityTypeConfiguration<FinancialTransaction> { public void Configure(EntityTypeBuilder<FinancialTransaction> b) { b.HasOne<Demand>().WithMany().HasForeignKey(x => x.DemandId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Payment>().WithMany().HasForeignKey(x => x.PaymentId).OnDelete(DeleteBehavior.Restrict); b.HasOne<ExpenseDisbursement>().WithMany().HasForeignKey(x => x.ExpenseDisbursementId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AccountAdjustment>().WithMany().HasForeignKey(x => x.AccountAdjustmentId).OnDelete(DeleteBehavior.Restrict); } }
