using BuildingManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BuildingManagement.Infrastructure;

internal sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> b) { ConfigurationHelpers.Entity(b, "Users"); b.Property(x => x.StatusKey).HasColumnType("varchar(40)").IsRequired(); b.HasIndex(x => x.StatusKey); }
}
internal sealed class UserLoginMethodConfiguration : IEntityTypeConfiguration<UserLoginMethod>
{
    public void Configure(EntityTypeBuilder<UserLoginMethod> b) { ConfigurationHelpers.Entity(b, "UserLoginMethods"); b.Property(x => x.LoginTypeKey).HasColumnType("varchar(30)").IsRequired(); b.Property(x => x.IdentifierValue).HasMaxLength(200).IsRequired(); b.Property(x => x.NormalizedIdentifierValue).HasMaxLength(200).IsRequired(); b.Property(x => x.StatusKey).HasColumnType("varchar(30)").IsRequired(); b.HasOne<User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => new { x.LoginTypeKey, x.NormalizedIdentifierValue }).IsUnique().HasFilter("[IsActive] = 1 AND [StatusKey] = 'active'"); b.HasIndex(x => new { x.UserId, x.IsPrimary }).IsUnique().HasFilter("[IsActive] = 1 AND [IsPrimary] = 1"); }
}
internal sealed class UserPartyLinkConfiguration : IEntityTypeConfiguration<UserPartyLink>
{
    public void Configure(EntityTypeBuilder<UserPartyLink> b) { ConfigurationHelpers.Entity(b, "UserPartyLinks"); b.HasOne<User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Party>().WithMany().HasForeignKey(x => x.PartyId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => x.PartyId).IsUnique().HasFilter("[IsActive] = 1"); b.HasIndex(x => new { x.UserId, x.IsPrimary }).IsUnique().HasFilter("[IsActive] = 1 AND [IsPrimary] = 1"); }
}
internal sealed class PartyAffiliationConfiguration : IEntityTypeConfiguration<PartyAffiliation>
{
    public void Configure(EntityTypeBuilder<PartyAffiliation> b) { ConfigurationHelpers.Entity(b, "PartyAffiliations"); b.Property(x => x.AffiliationTypeKey).HasColumnType("varchar(50)").IsRequired(); b.Property(x => x.Title).HasMaxLength(150); b.HasOne<Party>().WithMany().HasForeignKey(x => x.PersonPartyId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Party>().WithMany().HasForeignKey(x => x.OrganizationPartyId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => new { x.PersonPartyId, x.OrganizationPartyId, x.AffiliationTypeKey }); }
}
internal sealed class OtpChallengeConfiguration : IEntityTypeConfiguration<OtpChallenge>
{
    public void Configure(EntityTypeBuilder<OtpChallenge> b) { b.ToTable("OtpChallenges", "bms"); b.HasKey(x => x.Id); b.Property(x => x.Id).UseIdentityColumn(); b.Property(x => x.PublicReference).HasMaxLength(100).IsRequired(); b.Property(x => x.LoginTypeKey).HasColumnType("varchar(30)"); b.Property(x => x.IdentifierValue).HasMaxLength(200); b.Property(x => x.NormalizedIdentifierValue).HasMaxLength(200); b.Property(x => x.PurposeKey).HasColumnType("varchar(40)"); b.Property(x => x.CodeHash).HasMaxLength(128); b.Property(x => x.StatusKey).HasColumnType("varchar(30)"); b.Property(x => x.RowVersion).IsRowVersion().IsConcurrencyToken(); b.HasIndex(x => x.PublicReference).IsUnique(); b.HasIndex(x => new { x.NormalizedIdentifierValue, x.PurposeKey, x.StatusKey }); }
}
internal sealed class AuthSessionConfiguration : IEntityTypeConfiguration<AuthSession>
{
    public void Configure(EntityTypeBuilder<AuthSession> b) { ConfigurationHelpers.Entity(b, "AuthSessions"); b.ToTable("AuthSessions", "bms", t => t.HasCheckConstraint("CK_AuthSessions_OneActor", "(CASE WHEN [UserId] IS NULL THEN 0 ELSE 1 END + CASE WHEN [PlatformUserId] IS NULL THEN 0 ELSE 1 END) = 1")); b.Property(x => x.ClientTypeKey).HasColumnType("varchar(30)"); b.Property(x => x.StatusKey).HasColumnType("varchar(30)"); b.Property(x => x.AccessTokenHash).HasMaxLength(128).IsRequired(); b.HasIndex(x => x.AccessTokenHash).IsUnique(); b.HasOne<User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<PlatformUser>().WithMany().HasForeignKey(x => x.PlatformUserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<UserLoginMethod>().WithMany().HasForeignKey(x => x.AuthenticatedViaLoginMethodId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Complex>().WithMany().HasForeignKey(x => x.ActiveComplexId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Building>().WithMany().HasForeignKey(x => x.ActiveBuildingId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AccessRole>().WithMany().HasForeignKey(x => x.ActiveRoleId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => new { x.UserId, x.StatusKey }); }
}
internal sealed class AuthRefreshTokenConfiguration : IEntityTypeConfiguration<AuthRefreshToken>
{
    public void Configure(EntityTypeBuilder<AuthRefreshToken> b) { b.ToTable("AuthRefreshTokens", "bms"); b.HasKey(x => x.Id); b.Property(x => x.Id).UseIdentityColumn(); b.Property(x => x.TokenHash).HasMaxLength(128).IsRequired(); b.Property(x => x.RowVersion).IsRowVersion().IsConcurrencyToken(); b.HasIndex(x => x.TokenHash).IsUnique(); b.HasOne<AuthSession>().WithMany().HasForeignKey(x => x.AuthSessionId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AuthRefreshToken>().WithMany().HasForeignKey(x => x.ReplacedByRefreshTokenId).OnDelete(DeleteBehavior.Restrict); }
}
internal sealed class AccessRoleConfiguration : IEntityTypeConfiguration<AccessRole>
{
    public void Configure(EntityTypeBuilder<AccessRole> b)
    {
        ConfigurationHelpers.Reference(b, "AccessRoles"); b.Property(x => x.Description).HasMaxLength(500); var at = new DateTimeOffset(2026, 8, 14, 0, 0, 0, TimeSpan.Zero); b.HasData(
    new { Id = 1L, Key = "building_manager", Title = "مدیر ساختمان", SortOrder = 10, IsActive = true, CreatedAtUtc = at, IsSystemRole = true },
    new { Id = 2L, Key = "accountant", Title = "حسابدار", SortOrder = 20, IsActive = true, CreatedAtUtc = at, IsSystemRole = true },
    new { Id = 3L, Key = "unit_owner", Title = "مالک واحد", SortOrder = 30, IsActive = true, CreatedAtUtc = at, IsSystemRole = true },
    new { Id = 4L, Key = "unit_tenant", Title = "مستأجر واحد", SortOrder = 40, IsActive = true, CreatedAtUtc = at, IsSystemRole = true },
    new { Id = 5L, Key = "unit_resident", Title = "ساکن واحد", SortOrder = 50, IsActive = true, CreatedAtUtc = at, IsSystemRole = true },
    new { Id = 6L, Key = "complex_manager", Title = "مدیر مجتمع", SortOrder = 5, IsActive = true, CreatedAtUtc = at, IsSystemRole = true },
    new { Id = 7L, Key = "manager_assistant", Title = "دستیار مدیر", SortOrder = 15, IsActive = true, CreatedAtUtc = at, IsSystemRole = true },
    new { Id = 8L, Key = "unit_representative", Title = "نماینده واحد", SortOrder = 60, IsActive = true, CreatedAtUtc = at, IsSystemRole = true });
    }
}
internal sealed class AccessPermissionConfiguration : IEntityTypeConfiguration<AccessCapability>
{
    public void Configure(EntityTypeBuilder<AccessCapability> b)
    {
        ConfigurationHelpers.Reference(b, "Permissions"); b.Property(x => x.CategoryKey).HasColumnType("varchar(50)"); b.Property(x => x.Description).HasMaxLength(500); var at = new DateTimeOffset(2026, 8, 14, 0, 0, 0, TimeSpan.Zero); b.HasData(
    Seed(15, "complex_view", "مشاهده مجتمع", "physical", 150, at), Seed(16, "complex_manage", "مدیریت مجتمع", "physical", 160, at),
    Seed(17, "building_view", "مشاهده ساختمان", "physical", 170, at), Seed(18, "building_manage", "مدیریت ساختمان", "physical", 180, at),
    Seed(19, "unit_view", "مشاهده واحد", "physical", 190, at), Seed(20, "unit_manage", "مدیریت واحد", "physical", 200, at),
    Seed(21, "party_view", "مشاهده اشخاص", "party", 210, at), Seed(22, "party_manage", "مدیریت اشخاص", "party", 220, at),
    Seed(23, "occupancy_view", "مشاهده سکونت", "party", 230, at), Seed(24, "occupancy_manage", "مدیریت سکونت", "party", 240, at),
    Seed(25, "asset_view", "مشاهده دارایی", "assets", 250, at), Seed(26, "asset_manage", "مدیریت دارایی", "assets", 260, at),
    Seed(27, "asset_event_view", "مشاهده رویداد دارایی", "assets", 270, at), Seed(28, "asset_event_manage", "مدیریت رویداد دارایی", "assets", 280, at),
    Seed(29, "expense_view", "مشاهده هزینه", "finance", 290, at), Seed(30, "expense_create", "ایجاد هزینه", "finance", 300, at),
    Seed(31, "expense_update", "ویرایش هزینه", "finance", 310, at), Seed(32, "expense_finalize", "نهایی‌سازی هزینه", "finance", 320, at),
    Seed(33, "demand_view", "مشاهده مطالبه", "finance", 330, at), Seed(34, "demand_create", "ایجاد مطالبه", "finance", 340, at),
    Seed(35, "demand_update", "ویرایش مطالبه", "finance", 350, at), Seed(36, "demand_finalize", "نهایی‌سازی مطالبه", "finance", 360, at),
    Seed(37, "payment_view", "مشاهده پرداخت", "finance", 370, at), Seed(38, "payment_submit", "ثبت پرداخت", "finance", 380, at),
    Seed(39, "payment_confirm", "تأیید پرداخت", "finance", 390, at),
    Seed(40, "file_read", "مشاهده فایل", "files", 400, at), Seed(41, "file_read_confidential", "مشاهده فایل محرمانه", "files", 410, at),
    Seed(42, "membership_view", "مشاهده عضویت", "iam", 420, at), Seed(43, "membership_manage_scoped", "مدیریت عضویت", "iam", 430, at),
    Seed(44, "invitation_send", "ارسال دعوت", "iam", 440, at), Seed(45, "invitation_revoke", "لغو دعوت", "iam", 450, at),
    Seed(46, "access_grant_view", "مشاهده دسترسی تفویضی", "iam", 460, at), Seed(47, "access_grant_manage", "مدیریت دسترسی تفویضی", "iam", 470, at),
    Seed(48, "financial_unit_view_own", "مشاهده مالی واحد خود", "finance", 480, at),
    Seed(49, "financial_unit_view_other_summary", "مشاهده خلاصه مالی سایر واحدها", "finance", 490, at),
    Seed(50, "financial_unit_view_other_detail", "مشاهده جزئیات مالی سایر واحدها", "finance", 500, at),
    Seed(51, "financial_unit_pay", "پرداخت برای واحد", "finance", 510, at),
    Seed(52, "location_manage", "مدیریت موقعیت‌های مکانی", "physical", 520, at),
    Seed(53, "file_manage", "مدیریت فایل", "files", 530, at));
    }
    private static object Seed(long id, string key, string title, string category, int order, DateTimeOffset at) => new { Id = id, Key = key, Title = title, CategoryKey = category, SortOrder = order, IsActive = true, CreatedAtUtc = at };
}
internal sealed class AccessRolePermissionConfiguration : IEntityTypeConfiguration<AccessRoleCapability>
{
    public void Configure(EntityTypeBuilder<AccessRoleCapability> b)
    {
        b.ToTable("RolePermissions", "bms"); b.HasKey(x => x.Id); b.Property(x => x.Id).UseIdentityColumn(); b.Property(x => x.EffectKey).HasColumnType("varchar(10)"); b.HasIndex(x => new { x.RoleId, x.PermissionId }).IsUnique(); b.HasOne<AccessRole>().WithMany().HasForeignKey(x => x.RoleId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AccessCapability>().WithMany().HasForeignKey(x => x.PermissionId).OnDelete(DeleteBehavior.Restrict);
        var rows = new List<object>(); long id = 1;
        void Add(long role, params long[] permissions) { foreach (var permission in permissions) rows.Add(new { Id = id++, RoleId = role, PermissionId = permission, EffectKey = "allow" }); }
        Add(6, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53);
        Add(1, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53);
        Add(7, 17, 19, 21, 23, 25, 27, 29, 30, 31, 33, 34, 35, 37, 38, 40, 42, 44, 46, 48);
        Add(2, 17, 19, 21, 23, 25, 27, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 48, 49, 50, 51);
        Add(3, 17, 19, 21, 23, 25, 27, 29, 33, 37, 38, 40, 48, 51);
        Add(4, 17, 19, 23, 25, 27, 29, 33, 37, 38, 40, 48, 51);
        Add(5, 17, 19, 23, 25, 27, 29, 33, 37, 40, 48);
        Add(8, 17, 19, 23, 25, 27, 29, 33, 37, 38, 40, 48, 51);
        b.HasData(rows);
    }
}
internal sealed class RoleAllowedScopeConfiguration : IEntityTypeConfiguration<RoleAllowedScope>
{
    public void Configure(EntityTypeBuilder<RoleAllowedScope> b)
    {
        b.ToTable("RoleAllowedScopes", "bms"); b.HasKey(x => x.Id); b.Property(x => x.Id).UseIdentityColumn(); b.Property(x => x.ScopeKindKey).HasColumnType("varchar(20)"); b.HasOne<AccessRole>().WithMany().HasForeignKey(x => x.RoleId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => new { x.RoleId, x.ScopeKindKey }).IsUnique();
        b.HasData(new { Id = 1L, RoleId = 6L, ScopeKindKey = "complex" }, new { Id = 2L, RoleId = 1L, ScopeKindKey = "building" }, new { Id = 3L, RoleId = 7L, ScopeKindKey = "building" }, new { Id = 4L, RoleId = 2L, ScopeKindKey = "building" }, new { Id = 5L, RoleId = 3L, ScopeKindKey = "unit" }, new { Id = 6L, RoleId = 4L, ScopeKindKey = "unit" }, new { Id = 7L, RoleId = 5L, ScopeKindKey = "unit" }, new { Id = 8L, RoleId = 8L, ScopeKindKey = "unit" });
    }
}
internal sealed class AccessMembershipConfiguration : IEntityTypeConfiguration<AccessMembership>
{
    public void Configure(EntityTypeBuilder<AccessMembership> b) { ConfigurationHelpers.Entity(b, "AccessMemberships"); b.ToTable("AccessMemberships", "bms", t => t.HasCheckConstraint("CK_AccessMemberships_OneScope", "(CASE WHEN [ComplexId] IS NULL THEN 0 ELSE 1 END + CASE WHEN [BuildingId] IS NULL THEN 0 ELSE 1 END + CASE WHEN [UnitId] IS NULL THEN 0 ELSE 1 END) = 1")); b.Property(x => x.StatusKey).HasColumnType("varchar(30)"); b.HasOne<User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AccessRole>().WithMany().HasForeignKey(x => x.RoleId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Complex>().WithMany().HasForeignKey(x => x.ComplexId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Building>().WithMany().HasForeignKey(x => x.BuildingId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Unit>().WithMany().HasForeignKey(x => x.UnitId).OnDelete(DeleteBehavior.Restrict); b.HasOne<UnitPartyRelation>().WithMany().HasForeignKey(x => x.SourceUnitPartyRelationId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => new { x.UserId, x.RoleId, x.ComplexId, x.BuildingId, x.UnitId }).IsUnique().HasFilter("[IsActive] = 1 AND [EndsAtUtc] IS NULL"); }
}
internal sealed class AccessGrantConfiguration : IEntityTypeConfiguration<AccessGrant> { public void Configure(EntityTypeBuilder<AccessGrant> b) { ConfigurationHelpers.Entity(b, "AccessGrants"); b.ToTable("AccessGrants", "bms", t => t.HasCheckConstraint("CK_AccessGrants_OneScope", "(CASE WHEN [ComplexId] IS NULL THEN 0 ELSE 1 END + CASE WHEN [BuildingId] IS NULL THEN 0 ELSE 1 END + CASE WHEN [UnitId] IS NULL THEN 0 ELSE 1 END) = 1")); b.Property(x => x.Reason).HasMaxLength(500); b.HasOne<User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<User>().WithMany().HasForeignKey(x => x.GrantedByUserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AccessCapability>().WithMany().HasForeignKey(x => x.PermissionId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Complex>().WithMany().HasForeignKey(x => x.ComplexId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Building>().WithMany().HasForeignKey(x => x.BuildingId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Unit>().WithMany().HasForeignKey(x => x.UnitId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => new { x.UserId, x.PermissionId, x.ComplexId, x.BuildingId, x.UnitId }).IsUnique().HasFilter("[IsActive] = 1 AND [RevokedAtUtc] IS NULL"); } }
internal sealed class BuildingAccessSettingConfiguration : IEntityTypeConfiguration<BuildingAccessSetting> { public void Configure(EntityTypeBuilder<BuildingAccessSetting> b) { ConfigurationHelpers.Entity(b, "BuildingAccessSettings"); b.Property(x => x.UnitVisibilityKey).HasColumnType("varchar(30)"); b.Property(x => x.FinancialVisibilityKey).HasColumnType("varchar(30)"); b.HasOne<Building>().WithMany().HasForeignKey(x => x.BuildingId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => x.BuildingId).IsUnique(); } }
internal sealed class InvitationConfiguration : IEntityTypeConfiguration<Invitation> { public void Configure(EntityTypeBuilder<Invitation> b) { ConfigurationHelpers.Entity(b, "Invitations"); b.ToTable("Invitations", "bms", t => t.HasCheckConstraint("CK_Invitations_OneScope", "(CASE WHEN [ComplexId] IS NULL THEN 0 ELSE 1 END + CASE WHEN [BuildingId] IS NULL THEN 0 ELSE 1 END + CASE WHEN [UnitId] IS NULL THEN 0 ELSE 1 END) = 1")); b.Property(x => x.TokenHash).HasMaxLength(128); b.Property(x => x.NormalizedIdentifierValue).HasMaxLength(200); b.Property(x => x.InvitationTypeKey).HasColumnType("varchar(30)"); b.HasOne<AccessRole>().WithMany().HasForeignKey(x => x.RoleId).OnDelete(DeleteBehavior.Restrict); b.HasOne<User>().WithMany().HasForeignKey(x => x.InvitedByUserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<User>().WithMany().HasForeignKey(x => x.AcceptedByUserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Complex>().WithMany().HasForeignKey(x => x.ComplexId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Building>().WithMany().HasForeignKey(x => x.BuildingId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Unit>().WithMany().HasForeignKey(x => x.UnitId).OnDelete(DeleteBehavior.Restrict); b.HasOne<UnitPartyRelation>().WithMany().HasForeignKey(x => x.SourceUnitPartyRelationId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => x.TokenHash).IsUnique(); b.HasIndex(x => new { x.NormalizedIdentifierValue, x.RoleId, x.ComplexId, x.BuildingId, x.UnitId }).IsUnique().HasFilter("[AcceptedAtUtc] IS NULL AND [RevokedAtUtc] IS NULL AND [IsActive] = 1"); } }
internal sealed class MembershipExitRequestConfiguration : IEntityTypeConfiguration<MembershipExitRequest> { public void Configure(EntityTypeBuilder<MembershipExitRequest> b) { ConfigurationHelpers.Entity(b, "MembershipExitRequests"); b.Property(x => x.StatusKey).HasColumnType("varchar(30)"); b.Property(x => x.Reason).HasMaxLength(500); b.Property(x => x.DecisionReason).HasMaxLength(500); b.HasOne<AccessMembership>().WithMany().HasForeignKey(x => x.MembershipId).OnDelete(DeleteBehavior.Restrict); b.HasOne<User>().WithMany().HasForeignKey(x => x.RequestedByUserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<User>().WithMany().HasForeignKey(x => x.DecidedByUserId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => x.MembershipId).IsUnique().HasFilter("[IsActive] = 1 AND [StatusKey] = 'pending'"); } }
internal sealed class IdentityConflictReviewConfiguration : IEntityTypeConfiguration<IdentityConflictReview> { public void Configure(EntityTypeBuilder<IdentityConflictReview> b) { ConfigurationHelpers.Entity(b, "IdentityConflictReviews"); b.Property(x => x.ConflictTypeKey).HasColumnType("varchar(50)"); b.Property(x => x.StatusKey).HasColumnType("varchar(30)"); b.Property(x => x.Details).HasMaxLength(1000); b.HasOne<User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Party>().WithMany().HasForeignKey(x => x.PartyId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class AccountRecoveryCaseConfiguration : IEntityTypeConfiguration<AccountRecoveryCase> { public void Configure(EntityTypeBuilder<AccountRecoveryCase> b) { ConfigurationHelpers.Entity(b, "AccountRecoveryCases"); b.Property(x => x.ReferenceHash).HasMaxLength(128).IsRequired(); b.Property(x => x.RecoveryTypeKey).HasColumnType("varchar(40)"); b.Property(x => x.StatusKey).HasColumnType("varchar(30)"); b.Property(x => x.OldNormalizedIdentifier).HasMaxLength(200); b.Property(x => x.NewNormalizedIdentifier).HasMaxLength(200); b.Property(x => x.IdentityNumberEvidence).HasMaxLength(50); b.Property(x => x.Reason).HasMaxLength(1000); b.HasIndex(x => x.ReferenceHash).IsUnique(); b.HasOne<User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<UserLoginMethod>().WithMany().HasForeignKey(x => x.OldLoginMethodId).OnDelete(DeleteBehavior.Restrict); b.HasOne<PlatformUser>().WithMany().HasForeignKey(x => x.ResolvedByPlatformUserId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class PlatformUserConfiguration : IEntityTypeConfiguration<PlatformUser> { public void Configure(EntityTypeBuilder<PlatformUser> b) { ConfigurationHelpers.Entity(b, "PlatformUsers"); b.Property(x => x.Username).HasMaxLength(100); b.Property(x => x.NormalizedUsername).HasMaxLength(100); b.Property(x => x.PasswordHash).HasMaxLength(500); b.Property(x => x.StatusKey).HasColumnType("varchar(30)"); b.HasIndex(x => x.NormalizedUsername).IsUnique(); } }
internal sealed class PlatformRoleConfiguration : IEntityTypeConfiguration<PlatformRole> { public void Configure(EntityTypeBuilder<PlatformRole> b) { ConfigurationHelpers.Reference(b, "PlatformRoles"); var at = new DateTimeOffset(2026, 8, 15, 0, 0, 0, TimeSpan.Zero); b.HasData(new { Id = 1L, Key = "super_admin", Title = "مدیر کل پلتفرم", SortOrder = 10, IsActive = true, CreatedAtUtc = at }, new { Id = 2L, Key = "support_manager", Title = "مدیر پشتیبانی", SortOrder = 20, IsActive = true, CreatedAtUtc = at }, new { Id = 3L, Key = "support_agent", Title = "کارشناس پشتیبانی", SortOrder = 30, IsActive = true, CreatedAtUtc = at }); } }
internal sealed class PlatformPermissionConfiguration : IEntityTypeConfiguration<PlatformCapability> { public void Configure(EntityTypeBuilder<PlatformCapability> b) { ConfigurationHelpers.Reference(b, "PlatformPermissions"); var at = new DateTimeOffset(2026, 8, 15, 0, 0, 0, TimeSpan.Zero); b.HasData(new { Id = 1L, Key = "recovery_case_view", Title = "مشاهده پرونده بازیابی", SortOrder = 10, IsActive = true, CreatedAtUtc = at }, new { Id = 2L, Key = "recovery_case_review", Title = "بررسی پرونده بازیابی", SortOrder = 20, IsActive = true, CreatedAtUtc = at }, new { Id = 3L, Key = "support_act", Title = "نمایندگی پشتیبانی", SortOrder = 30, IsActive = true, CreatedAtUtc = at }, new { Id = 4L, Key = "support_act_view", Title = "مشاهده نمایندگی پشتیبانی", SortOrder = 40, IsActive = true, CreatedAtUtc = at }, new { Id = 5L, Key = "platform_user_manage", Title = "مدیریت کاربران پلتفرم", SortOrder = 50, IsActive = true, CreatedAtUtc = at }); } }
internal sealed class PlatformRolePermissionConfiguration : IEntityTypeConfiguration<PlatformRolePermissionLink> { public void Configure(EntityTypeBuilder<PlatformRolePermissionLink> b) { b.ToTable("PlatformRolePermissions", "bms"); b.HasKey(x => x.Id); b.Property(x => x.Id).UseIdentityColumn(); b.HasOne<PlatformRole>().WithMany().HasForeignKey(x => x.RoleId).OnDelete(DeleteBehavior.Restrict); b.HasOne<PlatformCapability>().WithMany().HasForeignKey(x => x.PermissionId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => new { x.RoleId, x.PermissionId }).IsUnique(); b.HasData(new { Id = 1L, RoleId = 1L, PermissionId = 1L }, new { Id = 2L, RoleId = 1L, PermissionId = 2L }, new { Id = 3L, RoleId = 1L, PermissionId = 3L }, new { Id = 4L, RoleId = 1L, PermissionId = 4L }, new { Id = 5L, RoleId = 1L, PermissionId = 5L }, new { Id = 6L, RoleId = 2L, PermissionId = 1L }, new { Id = 7L, RoleId = 2L, PermissionId = 2L }, new { Id = 8L, RoleId = 2L, PermissionId = 3L }, new { Id = 9L, RoleId = 2L, PermissionId = 4L }, new { Id = 10L, RoleId = 3L, PermissionId = 1L }); } }
internal sealed class PlatformUserRoleConfiguration : IEntityTypeConfiguration<PlatformUserRoleLink> { public void Configure(EntityTypeBuilder<PlatformUserRoleLink> b) { b.ToTable("PlatformUserRoles", "bms"); b.HasKey(x => x.Id); b.Property(x => x.Id).UseIdentityColumn(); b.HasOne<PlatformUser>().WithMany().HasForeignKey(x => x.PlatformUserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<PlatformRole>().WithMany().HasForeignKey(x => x.RoleId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => new { x.PlatformUserId, x.RoleId }).IsUnique(); } }
internal sealed class SupportActingSessionConfiguration : IEntityTypeConfiguration<SupportActingSession> { public void Configure(EntityTypeBuilder<SupportActingSession> b) { ConfigurationHelpers.Entity(b, "SupportActingSessions"); b.Property(x => x.TokenHash).HasMaxLength(128).IsRequired(); b.Property(x => x.Reason).HasMaxLength(1000); b.Property(x => x.TicketReference).HasMaxLength(200); b.Property(x => x.EndReasonKey).HasColumnType("varchar(40)"); b.HasIndex(x => x.TokenHash).IsUnique(); b.HasOne<PlatformUser>().WithMany().HasForeignKey(x => x.PlatformUserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<User>().WithMany().HasForeignKey(x => x.TargetUserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AuthSession>().WithMany().HasForeignKey(x => x.PlatformAuthSessionId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class SecurityAuditEventConfiguration : IEntityTypeConfiguration<SecurityAuditEvent> { public void Configure(EntityTypeBuilder<SecurityAuditEvent> b) { b.ToTable("SecurityAuditEvents", "bms"); b.HasKey(x => x.Id); b.Property(x => x.Id).UseIdentityColumn(); b.Property(x => x.EventTypeKey).HasColumnType("varchar(80)"); b.Property(x => x.ResourceKindKey).HasColumnType("varchar(50)"); b.Property(x => x.ResourceCode).HasMaxLength(100); b.Property(x => x.Reason).HasMaxLength(1000); b.Property(x => x.IpAddress).HasMaxLength(64); b.HasOne<User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<PlatformUser>().WithMany().HasForeignKey(x => x.PlatformUserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AuthSession>().WithMany().HasForeignKey(x => x.AuthSessionId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => new { x.UserId, x.OccurredAtUtc }); } }
internal sealed class BuildingRolePermissionOverrideConfiguration : IEntityTypeConfiguration<BuildingRolePermissionOverride> { public void Configure(EntityTypeBuilder<BuildingRolePermissionOverride> b) { ConfigurationHelpers.Entity(b, "BuildingRolePermissionOverrides"); b.Property(x => x.EffectKey).HasColumnType("varchar(10)"); b.HasOne<Building>().WithMany().HasForeignKey(x => x.BuildingId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AccessRole>().WithMany().HasForeignKey(x => x.RoleId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AccessCapability>().WithMany().HasForeignKey(x => x.PermissionId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => new { x.BuildingId, x.RoleId, x.PermissionId }).IsUnique(); } }
